import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { Octokit } from "octokit";
import type { RepositoryFacts } from "../analyze/summary";

const execFileAsync = promisify(execFile);
export const docsBranchName = "onboarding-pr-bot/docs";

export type PublishOnboardingPullRequestOptions = {
  owner: string;
  repo: string;
  repoPath: string;
  token: string;
  defaultBranch: string;
  files: string[];
  facts: RepositoryFacts;
};

export type PublishOnboardingPullRequestResult =
  | {
      status: "created" | "updated";
      branch: string;
      pullRequestUrl: string;
    }
  | {
      status: "no_changes";
      branch: string;
    };

export async function publishOnboardingPullRequest(
  options: PublishOnboardingPullRequestOptions,
): Promise<PublishOnboardingPullRequestResult> {
  await configureGitAuthor(options.repoPath);
  await fetchDocsBranchIfPresent(options.repoPath);
  await git(options.repoPath, ["checkout", "-B", docsBranchName]);
  await git(options.repoPath, ["add", ...options.files]);

  if (!(await hasStagedChanges(options.repoPath))) {
    return {
      status: "no_changes",
      branch: docsBranchName,
    };
  }

  await git(options.repoPath, ["commit", "-m", "Add onboarding documentation"]);
  await git(options.repoPath, ["push", "--force", "origin", docsBranchName]);

  const octokit = new Octokit({ auth: options.token });
  const existingPullRequestUrl = await findExistingPullRequestUrl(octokit, options);

  if (existingPullRequestUrl) {
    return {
      status: "updated",
      branch: docsBranchName,
      pullRequestUrl: existingPullRequestUrl,
    };
  }

  const pullRequest = await octokit.rest.pulls.create({
    owner: options.owner,
    repo: options.repo,
    title: "Add onboarding documentation",
    head: docsBranchName,
    base: options.defaultBranch,
    body: buildPullRequestBody(options.facts, options.files),
  });

  return {
    status: "created",
    branch: docsBranchName,
    pullRequestUrl: pullRequest.data.html_url,
  };
}

export function buildPullRequestBody(facts: RepositoryFacts, files: string[]): string {
  const detectedStack = facts.technologies.length
    ? facts.technologies.map((tech) => `${tech.name} (${tech.packageName})`).join(", ")
    : "No known framework packages detected";

  const healthNotes = facts.health.notes.length
    ? facts.health.notes.map((note) => `- ${note}`).join("\n")
    : "- No health notes were generated.";

  return [
    "This pull request was generated by Onboarding PR Bot.",
    "",
    "## What changed",
    "",
    ...files.map((file) => `- \`${file}\``),
    "",
    "## Verified repository facts",
    "",
    `- Package: ${facts.packageJson?.name ?? "not declared"}`,
    `- Package manager: ${facts.packageManager.name}${facts.packageManager.lockfile ? ` (${facts.packageManager.lockfile})` : ""}`,
    `- Entry points: ${facts.entryPoints.length ? facts.entryPoints.join(", ") : "none detected"}`,
    `- Detected stack: ${detectedStack}`,
    `- GitHub Actions workflows: ${facts.workflows.hasCi ? "present" : "missing"}`,
    "",
    "## Health notes",
    "",
    healthNotes,
    "",
    "No source code was executed while generating these files; the documentation is based on static repository analysis.",
  ].join("\n");
}

async function configureGitAuthor(repoPath: string): Promise<void> {
  await git(repoPath, ["config", "user.name", "onboarding-pr-bot"]);
  await git(repoPath, ["config", "user.email", "onboarding-pr-bot@users.noreply.github.com"]);
}

async function fetchDocsBranchIfPresent(repoPath: string): Promise<void> {
  try {
    await git(repoPath, [
      "fetch",
      "origin",
      `${docsBranchName}:refs/remotes/origin/${docsBranchName}`,
    ]);
  } catch {
    // The first bot run will not have a remote docs branch yet.
  }
}

async function hasStagedChanges(repoPath: string): Promise<boolean> {
  const { stdout } = await git(repoPath, ["diff", "--cached", "--name-only"]);
  return stdout.trim().length > 0;
}

async function findExistingPullRequestUrl(
  octokit: Octokit,
  options: PublishOnboardingPullRequestOptions,
): Promise<string | null> {
  const pullRequests = await octokit.rest.pulls.list({
    owner: options.owner,
    repo: options.repo,
    head: `${options.owner}:${docsBranchName}`,
    state: "open",
  });

  return pullRequests.data[0]?.html_url ?? null;
}

async function git(
  cwd: string,
  args: string[],
): Promise<{ stdout: string; stderr: string }> {
  return execFileAsync("git", args, {
    cwd,
    timeout: 120_000,
  });
}
