import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { Octokit } from "octokit";

const execFileAsync = promisify(execFile);
export const docsBranchName = "onboarding-pr-bot/docs";

export type PublishOnboardingPullRequestOptions = {
  owner: string;
  repo: string;
  repoPath: string;
  token: string;
  defaultBranch: string;
  files: string[];
};

export type PublishOnboardingPullRequestResult =
  | {
      status: "created" | "updated";
      branch: string;
      pullRequestUrl: string;
    }
  | {
      status: "no_changes";
      branch: string;
    };

export async function publishOnboardingPullRequest(
  options: PublishOnboardingPullRequestOptions,
): Promise<PublishOnboardingPullRequestResult> {
  await configureGitAuthor(options.repoPath);
  await fetchDocsBranchIfPresent(options.repoPath);
  await git(options.repoPath, ["checkout", "-B", docsBranchName]);
  await git(options.repoPath, ["add", ...options.files]);

  if (!(await hasStagedChanges(options.repoPath))) {
    return {
      status: "no_changes",
      branch: docsBranchName,
    };
  }

  await git(options.repoPath, ["commit", "-m", "Add onboarding documentation"]);
  await git(options.repoPath, ["push", "--force", "origin", docsBranchName]);

  const octokit = new Octokit({ auth: options.token });
  const existingPullRequestUrl = await findExistingPullRequestUrl(octokit, options);

  if (existingPullRequestUrl) {
    return {
      status: "updated",
      branch: docsBranchName,
      pullRequestUrl: existingPullRequestUrl,
    };
  }

  const pullRequest = await octokit.rest.pulls.create({
    owner: options.owner,
    repo: options.repo,
    title: "Add onboarding documentation",
    head: docsBranchName,
    base: options.defaultBranch,
    body: [
      "This pull request was generated by Onboarding PR Bot.",
      "",
      "It adds or refreshes onboarding documentation, a CODEMAP, and a health snapshot using static repository analysis.",
    ].join("\n"),
  });

  return {
    status: "created",
    branch: docsBranchName,
    pullRequestUrl: pullRequest.data.html_url,
  };
}

async function configureGitAuthor(repoPath: string): Promise<void> {
  await git(repoPath, ["config", "user.name", "onboarding-pr-bot"]);
  await git(repoPath, ["config", "user.email", "onboarding-pr-bot@users.noreply.github.com"]);
}

async function fetchDocsBranchIfPresent(repoPath: string): Promise<void> {
  try {
    await git(repoPath, [
      "fetch",
      "origin",
      `${docsBranchName}:refs/remotes/origin/${docsBranchName}`,
    ]);
  } catch {
    // The first bot run will not have a remote docs branch yet.
  }
}

async function hasStagedChanges(repoPath: string): Promise<boolean> {
  const { stdout } = await git(repoPath, ["diff", "--cached", "--name-only"]);
  return stdout.trim().length > 0;
}

async function findExistingPullRequestUrl(
  octokit: Octokit,
  options: PublishOnboardingPullRequestOptions,
): Promise<string | null> {
  const pullRequests = await octokit.rest.pulls.list({
    owner: options.owner,
    repo: options.repo,
    head: `${options.owner}:${docsBranchName}`,
    state: "open",
  });

  return pullRequests.data[0]?.html_url ?? null;
}

async function git(
  cwd: string,
  args: string[],
): Promise<{ stdout: string; stderr: string }> {
  return execFileAsync("git", args, {
    cwd,
    timeout: 120_000,
  });
}
